# Generated by Django 3.2.9 on 2021-11-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictip',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restrictip',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
