version: "3.9"


services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=r4min
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=r4min
    networks:
      - main
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    command: sh -c "python manage.py migrate && gunicorn challenge.wsgi -b 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/code/
      - ./static:/app/static
    depends_on:
      - postgres
    expose:
      - "8000"
    networks:
      - main
    restart: on-failure
  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - app
    image: nginx:latest
    networks:
      - main
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
networks:
  main:

volumes:
  postgres_data:
